# Generated by Django 2.2 on 2021-10-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='Book_Image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
